package TT.entity;
// Generated 08-dic-2016 16:07:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ArbolEspecie generated by hbm2java
 */
public class ArbolEspecie  implements java.io.Serializable {


     private Integer idEspecie;
     private String nombreEspecie;
     private Set<EspecieCaracteristicas> especieCaracteristicases = new HashSet<EspecieCaracteristicas>(0);

    public ArbolEspecie() {
    }

	
    public ArbolEspecie(String nombreEspecie) {
        this.nombreEspecie = nombreEspecie;
    }
    public ArbolEspecie(String nombreEspecie, Set<EspecieCaracteristicas> especieCaracteristicases) {
       this.nombreEspecie = nombreEspecie;
       this.especieCaracteristicases = especieCaracteristicases;
    }
   
    public Integer getIdEspecie() {
        return this.idEspecie;
    }
    
    public void setIdEspecie(Integer idEspecie) {
        this.idEspecie = idEspecie;
    }
    public String getNombreEspecie() {
        return this.nombreEspecie;
    }
    
    public void setNombreEspecie(String nombreEspecie) {
        this.nombreEspecie = nombreEspecie;
    }
    public Set<EspecieCaracteristicas> getEspecieCaracteristicases() {
        return this.especieCaracteristicases;
    }
    
    public void setEspecieCaracteristicases(Set<EspecieCaracteristicas> especieCaracteristicases) {
        this.especieCaracteristicases = especieCaracteristicases;
    }




}


