package TT.entity;
// Generated 08-dic-2016 16:07:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Copa generated by hbm2java
 */
public class Copa  implements java.io.Serializable {


     private Integer idCopa;
     private Double espesor;
     private Set<EspecieCaracteristicas> especieCaracteristicases = new HashSet<EspecieCaracteristicas>(0);

    public Copa() {
    }

    public Copa(Double espesor, Set<EspecieCaracteristicas> especieCaracteristicases) {
       this.espesor = espesor;
       this.especieCaracteristicases = especieCaracteristicases;
    }
   
    public Integer getIdCopa() {
        return this.idCopa;
    }
    
    public void setIdCopa(Integer idCopa) {
        this.idCopa = idCopa;
    }
    public Double getEspesor() {
        return this.espesor;
    }
    
    public void setEspesor(Double espesor) {
        this.espesor = espesor;
    }
    public Set<EspecieCaracteristicas> getEspecieCaracteristicases() {
        return this.especieCaracteristicases;
    }
    
    public void setEspecieCaracteristicases(Set<EspecieCaracteristicas> especieCaracteristicases) {
        this.especieCaracteristicases = especieCaracteristicases;
    }




}


