package TT.entity;
// Generated 08-dic-2016 16:07:03 by Hibernate Tools 4.3.1



/**
 * EspecieCaracteristicasId generated by hbm2java
 */
public class EspecieCaracteristicasId  implements java.io.Serializable {


     private int idEspecie;
     private int idRp;
     private int idRs;
     private int idTronco;
     private int idCopa;
     private int idHojas;

    public EspecieCaracteristicasId() {
    }

    public EspecieCaracteristicasId(int idEspecie, int idRp, int idRs, int idTronco, int idCopa, int idHojas) {
       this.idEspecie = idEspecie;
       this.idRp = idRp;
       this.idRs = idRs;
       this.idTronco = idTronco;
       this.idCopa = idCopa;
       this.idHojas = idHojas;
    }
   
    public int getIdEspecie() {
        return this.idEspecie;
    }
    
    public void setIdEspecie(int idEspecie) {
        this.idEspecie = idEspecie;
    }
    public int getIdRp() {
        return this.idRp;
    }
    
    public void setIdRp(int idRp) {
        this.idRp = idRp;
    }
    public int getIdRs() {
        return this.idRs;
    }
    
    public void setIdRs(int idRs) {
        this.idRs = idRs;
    }
    public int getIdTronco() {
        return this.idTronco;
    }
    
    public void setIdTronco(int idTronco) {
        this.idTronco = idTronco;
    }
    public int getIdCopa() {
        return this.idCopa;
    }
    
    public void setIdCopa(int idCopa) {
        this.idCopa = idCopa;
    }
    public int getIdHojas() {
        return this.idHojas;
    }
    
    public void setIdHojas(int idHojas) {
        this.idHojas = idHojas;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EspecieCaracteristicasId) ) return false;
		 EspecieCaracteristicasId castOther = ( EspecieCaracteristicasId ) other; 
         
		 return (this.getIdEspecie()==castOther.getIdEspecie())
 && (this.getIdRp()==castOther.getIdRp())
 && (this.getIdRs()==castOther.getIdRs())
 && (this.getIdTronco()==castOther.getIdTronco())
 && (this.getIdCopa()==castOther.getIdCopa())
 && (this.getIdHojas()==castOther.getIdHojas());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEspecie();
         result = 37 * result + this.getIdRp();
         result = 37 * result + this.getIdRs();
         result = 37 * result + this.getIdTronco();
         result = 37 * result + this.getIdCopa();
         result = 37 * result + this.getIdHojas();
         return result;
   }   


}


