package TT.entity;
// Generated 08-dic-2016 16:07:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hojas generated by hbm2java
 */
public class Hojas  implements java.io.Serializable {


     private Integer idHojas;
     private Double grosor;
     private Double diametro;
     private Double densidad;
     private Set<EspecieCaracteristicas> especieCaracteristicases = new HashSet<EspecieCaracteristicas>(0);

    public Hojas() {
    }

    public Hojas(Double grosor, Double diametro, Double densidad, Set<EspecieCaracteristicas> especieCaracteristicases) {
       this.grosor = grosor;
       this.diametro = diametro;
       this.densidad = densidad;
       this.especieCaracteristicases = especieCaracteristicases;
    }
   
    public Integer getIdHojas() {
        return this.idHojas;
    }
    
    public void setIdHojas(Integer idHojas) {
        this.idHojas = idHojas;
    }
    public Double getGrosor() {
        return this.grosor;
    }
    
    public void setGrosor(Double grosor) {
        this.grosor = grosor;
    }
    public Double getDiametro() {
        return this.diametro;
    }
    
    public void setDiametro(Double diametro) {
        this.diametro = diametro;
    }
    public Double getDensidad() {
        return this.densidad;
    }
    
    public void setDensidad(Double densidad) {
        this.densidad = densidad;
    }
    public Set<EspecieCaracteristicas> getEspecieCaracteristicases() {
        return this.especieCaracteristicases;
    }
    
    public void setEspecieCaracteristicases(Set<EspecieCaracteristicas> especieCaracteristicases) {
        this.especieCaracteristicases = especieCaracteristicases;
    }




}


